# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.cache/wt} [current_project]
set_property parent.project_path {C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.xpr} [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_cache_permissions disable [current_project]
add_files {{C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/characterLib.coe}}
read_mem {{C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/sources_1/imports/PmodOLED_Source/charLib.mif}}
read_vhdl -library xil_defaultlib {
  {C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/sources_1/imports/PmodOLED_Source/Delay.vhd}
  {C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/sources_1/new/MarioLib.vhd}
  {C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/sources_1/imports/PmodOLED_Source/OledExample.vhd}
  {C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/sources_1/imports/PmodOLED_Source/OledInit.vhd}
  {C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/sources_1/imports/PmodOLED_Source/SpiCtrl.vhd}
  {C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/sources_1/imports/PmodOLED_Source/PmodOLEDCtrl.vhd}
}
read_ip -quiet {{C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/sources_1/ip/charLib/charLib.xci}}
set_property used_in_implementation false [get_files -all {{c:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/sources_1/ip/charLib/charLib_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/constrs_1/imports/XDC/Nexys4_Master.xdc}}
set_property used_in_implementation false [get_files {{C:/Storage/facultate/SSC/Project Pmod OLED/Nexys4OLEDdemo/Nexys4OLEDdemo.srcs/constrs_1/imports/XDC/Nexys4_Master.xdc}}]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top PmodOLED -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef PmodOLED.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file PmodOLED_utilization_synth.rpt -pb PmodOLED_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
